name: Build

on:
    push:
        branches-ignore:
            - 'dependabot/**'
    workflow_dispatch: ~

jobs:
    tests:
        runs-on: ubuntu-22.04

        timeout-minutes: 50

        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.1"
                  extensions: intl
                  tools: symfony
                  coverage: none

            - run: composer config extra.symfony.require "^5.4"
            - run: composer install --no-interaction
            - run: composer validate --ansi --strict --no-check-publish
